import type { OrchestratorConfig } from "./src/types";

const config: OrchestratorConfig = {
  outputDir: "~/orchestrator/output",
  stalenessThresholdDays: 7,
  telegram: {
    enabled: true,
  },
  projects: [
    {
      name: "offero",
      repo: "leongcheefai/offero",
      branch: "master",
      type: "saas",
      platform: "web",
      status: "active",
      description: "Offero is a platform for creating and managing offers for your products and services.",
      priority: "high",
    },
    {
      name: "viaticus",
      repo: "first-to-fly/firsttofly-garage-viaticus",
      branch: "production",
      type: "client",
      platform: "both",
      status: "active",
      description: "Client mobile + web app",
      priority: "high",
      clientName: "Acme Corp",
      budget: { total: 50000, invoiced: 25000, currency: "USD" },
    },
    {
      name: "praxor",
      repo: "leongcheefai/praxor",
      branch: "main",
      type: "saas",
      platform: "web",
      status: "active",
      description: "Offero is a platform for creating and managing offers for your products and services.",
      priority: "medium",
    },
    {
      name: "onz-webapp",
      repo: "weikaikhoo/onz-webapp",
      branch: "main",
      type: "saas",
      platform: "web",
      status: "active",
      description: "Offero is a platform for creating and managing offers for your products and services.",
      priority: "medium",
    },
    {
      name: "vanta - team hub",
      repo: "kit9898/team-hub-",
      branch: "main",
      type: "saas",
      platform: "web",
      status: "active",
      description: "Offero is a platform for creating and managing offers for your products and services.",
      priority: "low",
    },
    {
      name: "vanta - workshop management",
      repo: "kit9898/workshop-management-system",
      branch: "main",
      type: "saas",
      platform: "web",
      status: "active",
      description: "Offero is a platform for creating and managing offers for your products and services.",
      priority: "low",
    },
    // {
    //   name: "old-tool",
    //   repo: "cheefai/old-tool",
    //   branch: "main",
    //   type: "micro-tool",
    //   platform: "web",
    //   status: "parked",
    //   description: "Utility tool (paused)",
    //   parkedReason: "Waiting for upstream API v2",
    //   reactivateWhen: "API v2 launches",
    // },
  ],
};

export default config;
