import type { OrchestratorConfig } from "./src/types";

const config: OrchestratorConfig = {
  outputDir: "~/orchestrator/output",
  stalenessThresholdDays: 7,
  telegram: {
    enabled: true,
  },
  ai: {
    model: "claude-haiku-4-5-20251001",
  },
  projects: [
    {
      name: "Offero",
      repo: "leongcheefai/offero",
      branch: "master",
      type: "saas",
      platform: "web",
      status: "active",
      description: "Offero is a platform for creating and managing offers for your products and services.",
      priority: "high",
    },
    {
      name: "Viaticus",
      repo: "first-to-fly/firsttofly-garage-viaticus",
      branch: "production",
      type: "saas",
      platform: "web",
      status: "parked",
      description: "DMC web app",
      priority: "high",
    },
    {
      name: "praxor",
      repo: "leongcheefai/praxor",
      branch: "main",
      type: "saas",
      platform: "web",
      status: "parked",
      description: "Praxor is a development studio for building web and mobile apps.",
      priority: "low",
    },
    {
      name: "Onz",
      repo: "weikaikhoo/onz-webapp",
      branch: "main",
      type: "saas",
      platform: "web",
      status: "active",
      description: "Onz is a web app for posting food reviews and recommendations.",
      priority: "medium",
    },
    {
      name: "Vanta - Team Hub",
      repo: "kit9898/team-hub-",
      branch: "main",
      type: "saas",
      platform: "web",
      status: "active",
      description: "Vanta Team Hub is a web for internal team management and collaboration.",
      priority: "low",
    },
    {
      name: "Vanta - Workshop Management",
      repo: "kit9898/workshop-management-system",
      branch: "main",
      type: "saas",
      platform: "web",
      status: "parked",
      description: "Vanta Workshop Management is a web app for managing workshops and projects.",
      priority: "low",
    },
    {
      name: "Praxor Orchestrator",
      repo: "leongcheefai/praxor-orchestrator",
      branch: "master",
      type: "micro-tool",
      platform: "cli",
      status: "active",
      description: "A lightweight, zero-dependency CLI tool that scans your project portfolio, gathers Git activity and development context, and generates briefings and registries — giving you a bird's-eye view of all your projects at a glance.",
      priority: "medium",
    },
    // {
    //   name: "old-tool",
    //   repo: "cheefai/old-tool",
    //   branch: "main",
    //   type: "micro-tool",
    //   platform: "web",
    //   status: "parked",
    //   description: "Utility tool (paused)",
    //   parkedReason: "Waiting for upstream API v2",
    //   reactivateWhen: "API v2 launches",
    // },
  ],
};

export default config;
