[build]
builder = "NIXPACKS"

[build.nixpacks]
providers = ["bun"]
aptPkgs = []
installCmd = "curl -fsSL https://bun.sh/install | bash && export BUN_INSTALL=\"$HOME/.bun\" && export PATH=\"$BUN_INSTALL/bin:$PATH\" && bun install"

[deploy]
startCommand = "export BUN_INSTALL=\"$HOME/.bun\" && export PATH=\"$BUN_INSTALL/bin:$PATH\" && bun run src/server.ts"
